### ISSUE TITLE
Server source

### ISSUE THREAD

**Issue by takaaptech** [fedofcoders/deep.io#1]
Do you have a plan for server side? I am looking for server solution for Unity game so i wonder what is the language of our server?
Thank so much!

**Comment by dmitmel** [comment]
Yeah, I'm currently working on the multiplayer. I'm using Unity's built-in multiplayer system called [UNet](https://docs.unity3d.com/Manual/UNet.html). I recommend you to watch [this tutorial](https://youtu.be/T_03RZTdIkk?list=PLPV2KyIb3jR5PhGqsO7G4PsbEC_Al-kPZ) on YouTube because it covers a lot of features of UNet.

My first choice was to use [socket.io](https://socket.io/) for both server and client side, but this would be too hard to implement, so I decided to use UNet because it's much easier to learn and build multiplayer games.

**Comment by takaaptech** [comment]
Great! I am looking for your update! Thank so much!
